package com.amazonaws.regions;

import com.amazonaws.services.s3.internal.Constants;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

class RegionDefaults {
    RegionDefaults() {
    }

    public static List<Region> getRegions() {
        ArrayList arrayList = new ArrayList();
        Region region = new Region("af-south-1", "amazonaws.com");
        arrayList.add(region);
        updateRegion(region, ServiceAbbreviations.Autoscaling, "autoscaling.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.Dynamodb, "dynamodb.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.EC2, "ec2.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "kms", "kms.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "lambda", "lambda.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "logs", "logs.af-south-1.amazonaws.com", false, true);
        updateRegion(region, "s3", "s3.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SNS, "sns.af-south-1.amazonaws.com", false, true);
        updateRegion(region, ServiceAbbreviations.SQS, "sqs.af-south-1.amazonaws.com", false, true);
        String str = ServiceAbbreviations.SQS;
        updateRegion(region, ServiceAbbreviations.STS, "sts.af-south-1.amazonaws.com", false, true);
        Region region2 = new Region("ap-northeast-1", "amazonaws.com");
        arrayList.add(region2);
        updateRegion(region2, ServiceAbbreviations.Autoscaling, "autoscaling.ap-northeast-1.amazonaws.com", false, true);
        String str2 = ServiceAbbreviations.Autoscaling;
        updateRegion(region2, "cognito-identity", "cognito-identity.ap-northeast-1.amazonaws.com", false, true);
        String str3 = "cognito-identity";
        updateRegion(region2, "cognito-idp", "cognito-idp.ap-northeast-1.amazonaws.com", false, true);
        String str4 = "cognito-idp";
        updateRegion(region2, "cognito-sync", "cognito-sync.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "data.iot", "data.iot.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.Dynamodb, "dynamodb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.EC2, "ec2.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.ElasticLoadbalancing, "elasticloadbalancing.ap-northeast-1.amazonaws.com", false, true);
        String str5 = ServiceAbbreviations.ElasticLoadbalancing;
        updateRegion(region2, "firehose", "firehose.ap-northeast-1.amazonaws.com", false, true);
        String str6 = "firehose";
        updateRegion(region2, "iot", "iot.ap-northeast-1.amazonaws.com", false, true);
        String str7 = "iot";
        updateRegion(region2, "kinesis", "kinesis.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "kms", "kms.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "lambda", "lambda.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "logs", "logs.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "polly", "polly.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, "s3", "s3.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.SimpleDB, "sdb.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.SNS, "sns.ap-northeast-1.amazonaws.com", false, true);
        String str8 = str;
        updateRegion(region2, str8, "sqs.ap-northeast-1.amazonaws.com", false, true);
        updateRegion(region2, ServiceAbbreviations.STS, "sts.ap-northeast-1.amazonaws.com", false, true);
        Region region3 = new Region("ap-northeast-2", "amazonaws.com");
        arrayList.add(region3);
        ArrayList arrayList2 = arrayList;
        updateRegion(region3, str2, "autoscaling.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str3, "cognito-identity.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str4, "cognito-idp.ap-northeast-2.amazonaws.com", false, true);
        String str9 = "cognito-sync";
        updateRegion(region3, str9, "cognito-sync.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "data.iot", "data.iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.Dynamodb, "dynamodb.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.EC2, "ec2.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str5, "elasticloadbalancing.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str7, "iot.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "kinesis", "kinesis.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "kms", "kms.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "lambda", "lambda.ap-northeast-2.amazonaws.com", false, true);
        String str10 = "logs";
        updateRegion(region3, str10, "logs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, "polly", "polly.ap-northeast-2.amazonaws.com", false, true);
        String str11 = "s3";
        updateRegion(region3, str11, "s3.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.SNS, "sns.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, str8, "sqs.ap-northeast-2.amazonaws.com", false, true);
        updateRegion(region3, ServiceAbbreviations.STS, "sts.ap-northeast-2.amazonaws.com", false, true);
        Region region4 = new Region("ap-south-1", "amazonaws.com");
        arrayList2.add(region4);
        String str12 = "amazonaws.com";
        updateRegion(region4, str2, "autoscaling.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str3, "cognito-identity.ap-south-1.amazonaws.com", false, true);
        String str13 = str4;
        updateRegion(region4, str13, "cognito-idp.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str9, "cognito-sync.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.Dynamodb, "dynamodb.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.EC2, "ec2.ap-south-1.amazonaws.com", false, true);
        String str14 = ServiceAbbreviations.EC2;
        String str15 = str5;
        updateRegion(region4, str15, "elasticloadbalancing.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "kinesis", "kinesis.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "kms", "kms.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, "lambda", "lambda.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str10, "logs.ap-south-1.amazonaws.com", false, true);
        String str16 = str10;
        String str17 = "polly";
        updateRegion(region4, str17, "polly.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str11, "s3.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.SNS, "sns.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, str8, "sqs.ap-south-1.amazonaws.com", false, true);
        updateRegion(region4, ServiceAbbreviations.STS, "sts.ap-south-1.amazonaws.com", false, true);
        Region region5 = new Region("ap-southeast-1", str12);
        arrayList2.add(region5);
        String str18 = str2;
        String str19 = ServiceAbbreviations.STS;
        updateRegion(region5, str18, "autoscaling.ap-southeast-1.amazonaws.com", false, true);
        String str20 = str18;
        String str21 = str3;
        updateRegion(region5, str21, "cognito-identity.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str13, "cognito-idp.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str9, "cognito-sync.ap-southeast-1.amazonaws.com", false, true);
        String str22 = str9;
        String str23 = "data.iot";
        updateRegion(region5, str23, "data.iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, ServiceAbbreviations.Dynamodb, "dynamodb.ap-southeast-1.amazonaws.com", false, true);
        String str24 = ServiceAbbreviations.Dynamodb;
        String str25 = str14;
        updateRegion(region5, str25, "ec2.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str15, "elasticloadbalancing.ap-southeast-1.amazonaws.com", false, true);
        String str26 = str15;
        String str27 = str7;
        updateRegion(region5, str27, "iot.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "kinesis", "kinesis.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "kms", "kms.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, "lambda", "lambda.ap-southeast-1.amazonaws.com", false, true);
        String str28 = str16;
        updateRegion(region5, str28, "logs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str17, "polly.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str11, "s3.ap-southeast-1.amazonaws.com", false, true);
        String str29 = str11;
        updateRegion(region5, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, ServiceAbbreviations.SNS, "sns.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str8, "sqs.ap-southeast-1.amazonaws.com", false, true);
        updateRegion(region5, str19, "sts.ap-southeast-1.amazonaws.com", false, true);
        Region region6 = new Region("ap-southeast-2", str12);
        arrayList2.add(region6);
        String str30 = str20;
        updateRegion(region6, str30, "autoscaling.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str21, "cognito-identity.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str13, "cognito-idp.ap-southeast-2.amazonaws.com", false, true);
        String str31 = str13;
        String str32 = str22;
        updateRegion(region6, str32, "cognito-sync.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str23, "data.iot.ap-southeast-2.amazonaws.com", false, true);
        String str33 = str23;
        String str34 = str24;
        updateRegion(region6, str34, "dynamodb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str25, "ec2.ap-southeast-2.amazonaws.com", false, true);
        String str35 = str32;
        String str36 = str26;
        updateRegion(region6, str36, "elasticloadbalancing.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str27, "iot.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "kinesis", "kinesis.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, "kms", "kms.ap-southeast-2.amazonaws.com", false, true);
        String str37 = str27;
        String str38 = "lambda";
        updateRegion(region6, str38, "lambda.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str28, "logs.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str17, "polly.ap-southeast-2.amazonaws.com", false, true);
        String str39 = str21;
        updateRegion(region6, str29, "s3.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, ServiceAbbreviations.SNS, "sns.ap-southeast-2.amazonaws.com", false, true);
        updateRegion(region6, str8, "sqs.ap-southeast-2.amazonaws.com", false, true);
        String str40 = str19;
        updateRegion(region6, str40, "sts.ap-southeast-2.amazonaws.com", false, true);
        Region region7 = new Region("ca-central-1", str12);
        arrayList2.add(region7);
        updateRegion(region7, str30, "autoscaling.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str34, "dynamodb.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str25, "ec2.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str36, "elasticloadbalancing.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "kinesis", "kinesis.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, "kms", "kms.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str38, "lambda.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str28, "logs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str17, "polly.ca-central-1.amazonaws.com", false, true);
        String str41 = str17;
        String str42 = str29;
        updateRegion(region7, str42, "s3.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, ServiceAbbreviations.SNS, "sns.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str8, "sqs.ca-central-1.amazonaws.com", false, true);
        updateRegion(region7, str40, "sts.ca-central-1.amazonaws.com", false, true);
        Region region8 = new Region("eu-central-1", str12);
        arrayList2.add(region8);
        updateRegion(region8, str30, "autoscaling.eu-central-1.amazonaws.com", false, true);
        String str43 = str30;
        updateRegion(region8, str39, "cognito-identity.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str31, "cognito-idp.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str35, "cognito-sync.eu-central-1.amazonaws.com", false, true);
        String str44 = str33;
        updateRegion(region8, str44, "data.iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str34, "dynamodb.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str25, "ec2.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str36, "elasticloadbalancing.eu-central-1.amazonaws.com", false, true);
        String str45 = str36;
        updateRegion(region8, str6, "firehose.eu-central-1.amazonaws.com", false, true);
        String str46 = str37;
        updateRegion(region8, str46, "iot.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "kinesis", "kinesis.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, "kms", "kms.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str38, "lambda.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str28, "logs.eu-central-1.amazonaws.com", false, true);
        String str47 = str28;
        String str48 = str41;
        updateRegion(region8, str48, "polly.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str42, "s3.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, ServiceAbbreviations.SNS, "sns.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str8, "sqs.eu-central-1.amazonaws.com", false, true);
        updateRegion(region8, str40, "sts.eu-central-1.amazonaws.com", false, true);
        Region region9 = new Region("eu-central-2", str12);
        arrayList2.add(region9);
        updateRegion(region9, str43, "autoscaling.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str39, "cognito-identity.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str31, "cognito-idp.eu-central-2.amazonaws.com", false, true);
        String str49 = str35;
        updateRegion(region9, str49, "cognito-sync.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str44, "data.iot.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str34, "dynamodb.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str25, "ec2.eu-central-2.amazonaws.com", false, true);
        String str50 = str44;
        String str51 = str45;
        updateRegion(region9, str51, "elasticloadbalancing.eu-central-2.amazonaws.com", false, true);
        String str52 = str49;
        String str53 = str6;
        updateRegion(region9, str53, "firehose.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str46, "iot.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "kinesis", "kinesis.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, "kms", "kms.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str38, "lambda.eu-central-2.amazonaws.com", false, true);
        String str54 = str47;
        updateRegion(region9, str54, "logs.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str48, "polly.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str42, "s3.eu-central-2.amazonaws.com", false, true);
        String str55 = str48;
        updateRegion(region9, ServiceAbbreviations.SimpleDB, "sdb.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, ServiceAbbreviations.SNS, "sns.eu-central-2.amazonaws.com", false, true);
        updateRegion(region9, str8, "sqs.eu-central-2.amazonaws.com", false, true);
        String str56 = str40;
        updateRegion(region9, str56, "sts.eu-central-2.amazonaws.com", false, true);
        String str57 = str12;
        Region region10 = new Region("eu-south-1", str57);
        ArrayList arrayList3 = arrayList2;
        arrayList3.add(region10);
        String str58 = "kinesis";
        String str59 = str46;
        String str60 = str53;
        String str61 = str43;
        updateRegion(region10, str61, "autoscaling.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, str34, "dynamodb.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, str25, "ec2.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, str51, "elasticloadbalancing.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, str38, "lambda.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, str54, "logs.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, str42, "s3.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, ServiceAbbreviations.SNS, "sns.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, str8, "sqs.eu-south-1.amazonaws.com", false, true);
        updateRegion(region10, str56, "sts.eu-south-1.amazonaws.com", false, true);
        Region region11 = new Region("eu-south-2", str57);
        arrayList3.add(region11);
        updateRegion(region11, str61, "autoscaling.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str39, "cognito-identity.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str31, "cognito-idp.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str52, "cognito-sync.eu-south-2.amazonaws.com", false, true);
        String str62 = str50;
        updateRegion(region11, str62, "data.iot.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str34, "dynamodb.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str25, "ec2.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str51, "elasticloadbalancing.eu-south-2.amazonaws.com", false, true);
        String str63 = str51;
        updateRegion(region11, str60, "firehose.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str59, "iot.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str58, "kinesis.eu-south-2.amazonaws.com", false, true);
        String str64 = "kms";
        updateRegion(region11, str64, "kms.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str38, "lambda.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str54, "logs.eu-south-2.amazonaws.com", false, true);
        String str65 = str54;
        String str66 = str55;
        updateRegion(region11, str66, "polly.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str42, "s3.eu-south-2.amazonaws.com", false, true);
        String str67 = str42;
        updateRegion(region11, ServiceAbbreviations.SimpleDB, "sdb.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, ServiceAbbreviations.SNS, "sns.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str8, "sqs.eu-south-2.amazonaws.com", false, true);
        updateRegion(region11, str56, "sts.eu-south-2.amazonaws.com", false, true);
        Region region12 = new Region("eu-west-1", str57);
        arrayList3.add(region12);
        updateRegion(region12, str43, "autoscaling.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str39, "cognito-identity.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str31, "cognito-idp.eu-west-1.amazonaws.com", false, true);
        String str68 = str52;
        updateRegion(region12, str68, "cognito-sync.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str62, "data.iot.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str34, "dynamodb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str25, "ec2.eu-west-1.amazonaws.com", false, true);
        String str69 = str62;
        updateRegion(region12, str63, "elasticloadbalancing.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "email", "email.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str60, "firehose.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str59, "iot.eu-west-1.amazonaws.com", false, true);
        String str70 = str58;
        updateRegion(region12, str70, "kinesis.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str64, "kms.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str38, "lambda.eu-west-1.amazonaws.com", false, true);
        String str71 = str38;
        updateRegion(region12, str65, "logs.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "machinelearning", "machinelearning.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str66, "polly.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, "rekognition", "rekognition.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str67, "s3.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, ServiceAbbreviations.SimpleDB, "sdb.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, ServiceAbbreviations.SNS, "sns.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str8, "sqs.eu-west-1.amazonaws.com", false, true);
        updateRegion(region12, str56, "sts.eu-west-1.amazonaws.com", false, true);
        Region region13 = new Region("eu-west-2", str57);
        arrayList3.add(region13);
        updateRegion(region13, str43, "autoscaling.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str39, "cognito-identity.eu-west-2.amazonaws.com", false, true);
        String str72 = str31;
        updateRegion(region13, str72, "cognito-idp.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str68, "cognito-sync.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str34, "dynamodb.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str25, "ec2.eu-west-2.amazonaws.com", false, true);
        String str73 = str68;
        String str74 = str63;
        updateRegion(region13, str74, "elasticloadbalancing.eu-west-2.amazonaws.com", false, true);
        String str75 = str72;
        updateRegion(region13, str59, "iot.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str70, "kinesis.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str64, "kms.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str71, "lambda.eu-west-2.amazonaws.com", false, true);
        String str76 = str65;
        updateRegion(region13, str76, "logs.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str66, "polly.eu-west-2.amazonaws.com", false, true);
        String str77 = str66;
        String str78 = str67;
        updateRegion(region13, str78, "s3.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, ServiceAbbreviations.SNS, "sns.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str8, "sqs.eu-west-2.amazonaws.com", false, true);
        updateRegion(region13, str56, "sts.eu-west-2.amazonaws.com", false, true);
        Region region14 = new Region("eu-west-3", str57);
        arrayList3.add(region14);
        ArrayList arrayList4 = arrayList3;
        String str79 = str43;
        updateRegion(region14, str79, "autoscaling.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str34, "dynamodb.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str25, "ec2.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str74, "elasticloadbalancing.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str70, "kinesis.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str64, "kms.eu-west-3.amazonaws.com", false, true);
        String str80 = str64;
        String str81 = str71;
        updateRegion(region14, str81, "lambda.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str76, "logs.eu-west-3.amazonaws.com", false, true);
        String str82 = str76;
        String str83 = str77;
        updateRegion(region14, str83, "polly.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str78, "s3.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, ServiceAbbreviations.SNS, "sns.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str8, "sqs.eu-west-3.amazonaws.com", false, true);
        updateRegion(region14, str56, "sts.eu-west-3.amazonaws.com", false, true);
        Region region15 = new Region("sa-east-1", str57);
        arrayList4.add(region15);
        updateRegion(region15, str79, "autoscaling.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str34, "dynamodb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str25, "ec2.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str74, "elasticloadbalancing.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str70, "kinesis.sa-east-1.amazonaws.com", false, true);
        String str84 = str70;
        String str85 = str80;
        updateRegion(region15, str85, "kms.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str81, "lambda.sa-east-1.amazonaws.com", false, true);
        String str86 = str81;
        String str87 = str82;
        updateRegion(region15, str87, "logs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str83, "polly.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str78, "s3.sa-east-1.amazonaws.com", false, true);
        String str88 = str78;
        updateRegion(region15, ServiceAbbreviations.SimpleDB, "sdb.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, ServiceAbbreviations.SNS, "sns.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str8, "sqs.sa-east-1.amazonaws.com", false, true);
        updateRegion(region15, str56, "sts.sa-east-1.amazonaws.com", false, true);
        Region region16 = new Region("us-east-1", str57);
        ArrayList arrayList5 = arrayList4;
        arrayList5.add(region16);
        updateRegion(region16, str79, "autoscaling.us-east-1.amazonaws.com", false, true);
        String str89 = str79;
        updateRegion(region16, str39, "cognito-identity.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str75, "cognito-idp.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str73, "cognito-sync.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str69, "data.iot.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str34, "dynamodb.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str25, "ec2.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str74, "elasticloadbalancing.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "email", "email.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str60, "firehose.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str59, "iot.us-east-1.amazonaws.com", false, true);
        String str90 = str84;
        updateRegion(region16, str90, "kinesis.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str85, "kms.us-east-1.amazonaws.com", false, true);
        String str91 = str85;
        String str92 = str86;
        updateRegion(region16, str92, "lambda.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str87, "logs.us-east-1.amazonaws.com", false, true);
        String str93 = str87;
        updateRegion(region16, "machinelearning", "machinelearning.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "mobileanalytics", "mobileanalytics.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "pinpoint", "pinpoint.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str83, "polly.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, "rekognition", "rekognition.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str88, Constants.S3_HOSTNAME, false, true);
        updateRegion(region16, ServiceAbbreviations.SimpleDB, "sdb.amazonaws.com", false, true);
        updateRegion(region16, ServiceAbbreviations.SNS, "sns.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str8, "sqs.us-east-1.amazonaws.com", false, true);
        updateRegion(region16, str56, "sts.us-east-1.amazonaws.com", false, true);
        Region region17 = new Region("us-east-2", str57);
        arrayList5.add(region17);
        updateRegion(region17, str89, "autoscaling.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str39, "cognito-identity.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str75, "cognito-idp.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str73, "cognito-sync.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str34, "dynamodb.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str25, "ec2.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str74, "elasticloadbalancing.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str60, "firehose.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str59, "iot.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str90, "kinesis.us-east-2.amazonaws.com", false, true);
        String str94 = str91;
        updateRegion(region17, str94, "kms.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str92, "lambda.us-east-2.amazonaws.com", false, true);
        String str95 = str92;
        String str96 = str93;
        updateRegion(region17, str96, "logs.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str83, "polly.us-east-2.amazonaws.com", false, true);
        String str97 = str83;
        String str98 = str88;
        updateRegion(region17, str98, "s3.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, ServiceAbbreviations.SNS, "sns.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str8, "sqs.us-east-2.amazonaws.com", false, true);
        updateRegion(region17, str56, "sts.us-east-2.amazonaws.com", false, true);
        Region region18 = new Region("us-west-1", str57);
        arrayList5.add(region18);
        ArrayList arrayList6 = arrayList5;
        String str99 = str89;
        updateRegion(region18, str99, "autoscaling.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str34, "dynamodb.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str25, "ec2.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str74, "elasticloadbalancing.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str90, "kinesis.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str94, "kms.us-west-1.amazonaws.com", false, true);
        String str100 = str94;
        String str101 = str95;
        updateRegion(region18, str101, "lambda.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str96, "logs.us-west-1.amazonaws.com", false, true);
        String str102 = str96;
        String str103 = str97;
        updateRegion(region18, str103, "polly.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str98, "s3.us-west-1.amazonaws.com", false, true);
        String str104 = str98;
        updateRegion(region18, ServiceAbbreviations.SimpleDB, "sdb.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, ServiceAbbreviations.SNS, "sns.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str8, "sqs.us-west-1.amazonaws.com", false, true);
        updateRegion(region18, str56, "sts.us-west-1.amazonaws.com", false, true);
        Region region19 = new Region("us-west-2", str57);
        ArrayList arrayList7 = arrayList6;
        arrayList7.add(region19);
        updateRegion(region19, str99, "autoscaling.us-west-2.amazonaws.com", false, true);
        String str105 = str57;
        updateRegion(region19, str39, "cognito-identity.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str75, "cognito-idp.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str73, "cognito-sync.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str69, "data.iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str34, "dynamodb.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str25, "ec2.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str74, "elasticloadbalancing.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, "email", "email.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str60, "firehose.us-west-2.amazonaws.com", false, true);
        String str106 = str59;
        updateRegion(region19, str106, "iot.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str90, "kinesis.us-west-2.amazonaws.com", false, true);
        String str107 = str90;
        updateRegion(region19, str100, "kms.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str101, "lambda.us-west-2.amazonaws.com", false, true);
        String str108 = str102;
        updateRegion(region19, str108, "logs.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str103, "polly.us-west-2.amazonaws.com", false, true);
        String str109 = str103;
        updateRegion(region19, "rekognition", "rekognition.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str104, "s3.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, ServiceAbbreviations.SimpleDB, "sdb.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, ServiceAbbreviations.SNS, "sns.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str8, "sqs.us-west-2.amazonaws.com", false, true);
        updateRegion(region19, str56, "sts.us-west-2.amazonaws.com", false, true);
        Region region20 = new Region("cn-north-1", "amazonaws.com.cn");
        arrayList7.add(region20);
        updateRegion(region20, str99, "autoscaling.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str39, "cognito-identity.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str34, "dynamodb.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str25, "ec2.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str74, "elasticloadbalancing.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str106, "iot.cn-north-1.amazonaws.com.cn", false, true);
        String str110 = str107;
        updateRegion(region20, str110, "kinesis.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str101, "lambda.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str108, "logs.cn-north-1.amazonaws.com.cn", false, true);
        String str111 = str106;
        String str112 = str104;
        updateRegion(region20, str112, "s3.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, ServiceAbbreviations.SNS, "sns.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str8, "sqs.cn-north-1.amazonaws.com.cn", false, true);
        updateRegion(region20, str56, "sts.cn-north-1.amazonaws.com.cn", false, true);
        Region region21 = new Region("cn-northwest-1", "amazonaws.com.cn");
        arrayList7.add(region21);
        updateRegion(region21, str99, "autoscaling.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, str34, "dynamodb.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, str25, "ec2.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, str74, "elasticloadbalancing.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, str110, "kinesis.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, str108, "logs.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, str112, "s3.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, ServiceAbbreviations.SNS, "sns.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, str8, "sqs.cn-northwest-1.amazonaws.com.cn", false, true);
        updateRegion(region21, str56, "sts.cn-northwest-1.amazonaws.com.cn", false, true);
        String str113 = str105;
        Region region22 = new Region("us-gov-west-1", str113);
        arrayList7.add(region22);
        updateRegion(region22, str99, "autoscaling.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str34, "dynamodb.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str25, "ec2.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str74, "elasticloadbalancing.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str110, "kinesis.us-gov-west-1.amazonaws.com", false, true);
        String str114 = str110;
        String str115 = str100;
        updateRegion(region22, str115, "kms.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str101, "lambda.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str108, "logs.us-gov-west-1.amazonaws.com", false, true);
        String str116 = str108;
        updateRegion(region22, "rekognition", "rekognition.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str112, "s3.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, ServiceAbbreviations.SNS, "sns.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str8, "sqs.us-gov-west-1.amazonaws.com", false, true);
        updateRegion(region22, str56, "sts.us-gov-west-1.amazonaws.com", false, true);
        Region region23 = new Region("us-gov-east-1", str113);
        ArrayList arrayList8 = arrayList7;
        arrayList8.add(region23);
        updateRegion(region23, str99, "autoscaling.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, str34, "dynamodb.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, str25, "ec2.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, str74, "elasticloadbalancing.us-gov-east-1.amazonaws.com", false, true);
        String str117 = str74;
        String str118 = str114;
        updateRegion(region23, str118, "kinesis.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, str115, "kms.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, str101, "lambda.us-gov-east-1.amazonaws.com", false, true);
        String str119 = str101;
        updateRegion(region23, str116, "logs.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, "rekognition", "rekognition.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, str112, "s3.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, ServiceAbbreviations.SNS, "sns.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, str8, "sqs.us-gov-east-1.amazonaws.com", false, true);
        updateRegion(region23, str56, "sts.us-gov-east-1.amazonaws.com", false, true);
        Region region24 = new Region("eu-north-1", str113);
        arrayList8.add(region24);
        updateRegion(region24, str99, "autoscaling.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str34, "dynamodb.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str25, "ec2.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str117, "elasticloadbalancing.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str60, "firehose.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str111, "iot.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str118, "kinesis.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str115, "kms.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str119, "lambda.eu-north-1.amazonaws.com", false, true);
        String str120 = str116;
        updateRegion(region24, str120, "logs.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str112, "s3.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, ServiceAbbreviations.SNS, "sns.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str8, "sqs.eu-north-1.amazonaws.com", false, true);
        updateRegion(region24, str56, "sts.eu-north-1.amazonaws.com", false, true);
        Region region25 = new Region("ap-east-1", str113);
        arrayList8.add(region25);
        updateRegion(region25, str99, "autoscaling.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, str34, "dynamodb.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, str25, "ec2.ap-east-1.amazonaws.com", false, true);
        String str121 = str25;
        updateRegion(region25, str117, "elasticloadbalancing.ap-east-1.amazonaws.com", false, true);
        String str122 = str60;
        updateRegion(region25, str122, "firehose.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, str118, "kinesis.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, str115, "kms.ap-east-1.amazonaws.com", false, true);
        String str123 = str115;
        String str124 = str119;
        updateRegion(region25, str124, "lambda.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, str120, "logs.ap-east-1.amazonaws.com", false, true);
        String str125 = str120;
        String str126 = str109;
        updateRegion(region25, str126, "polly.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, str112, "s3.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, ServiceAbbreviations.SNS, "sns.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, str8, "sqs.ap-east-1.amazonaws.com", false, true);
        updateRegion(region25, str56, "sts.ap-east-1.amazonaws.com", false, true);
        Region region26 = new Region("me-south-1", str113);
        arrayList8.add(region26);
        updateRegion(region26, str99, "autoscaling.me-south-1.amazonaws.com", false, true);
        String str127 = str99;
        updateRegion(region26, str39, "cognito-identity.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str75, "cognito-idp.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str73, "cognito-sync.me-south-1.amazonaws.com", false, true);
        String str128 = str69;
        updateRegion(region26, str128, "data.iot.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str34, "dynamodb.me-south-1.amazonaws.com", false, true);
        String str129 = str34;
        updateRegion(region26, str121, "ec2.me-south-1.amazonaws.com", false, true);
        String str130 = str117;
        updateRegion(region26, str130, "elasticloadbalancing.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str122, "firehose.me-south-1.amazonaws.com", false, true);
        String str131 = str122;
        String str132 = str111;
        updateRegion(region26, str132, "iot.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str118, "kinesis.me-south-1.amazonaws.com", false, true);
        String str133 = str118;
        String str134 = str123;
        updateRegion(region26, str134, "kms.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str124, "lambda.me-south-1.amazonaws.com", false, true);
        String str135 = str124;
        String str136 = str125;
        updateRegion(region26, str136, "logs.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str126, "polly.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str112, "s3.me-south-1.amazonaws.com", false, true);
        String str137 = str112;
        updateRegion(region26, ServiceAbbreviations.SimpleDB, "sdb.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, ServiceAbbreviations.SNS, "sns.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str8, "sqs.me-south-1.amazonaws.com", false, true);
        updateRegion(region26, str56, "sts.me-south-1.amazonaws.com", false, true);
        Region region27 = new Region("ap-southeast-3", str113);
        arrayList8.add(region27);
        updateRegion(region27, str127, "autoscaling.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str39, "cognito-identity.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str75, "cognito-idp.ap-southeast-3.amazonaws.com", false, true);
        String str138 = str73;
        updateRegion(region27, str138, "cognito-sync.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str128, "data.iot.ap-southeast-3.amazonaws.com", false, true);
        String str139 = str128;
        updateRegion(region27, str129, "dynamodb.ap-southeast-3.amazonaws.com", false, true);
        String str140 = str121;
        updateRegion(region27, str140, "ec2.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str130, "elasticloadbalancing.ap-southeast-3.amazonaws.com", false, true);
        String str141 = str130;
        String str142 = str131;
        updateRegion(region27, str142, "firehose.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str132, "iot.ap-southeast-3.amazonaws.com", false, true);
        String str143 = str132;
        String str144 = str133;
        updateRegion(region27, str144, "kinesis.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str134, "kms.ap-southeast-3.amazonaws.com", false, true);
        String str145 = str134;
        String str146 = str135;
        updateRegion(region27, str146, "lambda.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str136, "logs.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str126, "polly.ap-southeast-3.amazonaws.com", false, true);
        String str147 = str126;
        updateRegion(region27, str137, "s3.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, ServiceAbbreviations.SNS, "sns.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str8, "sqs.ap-southeast-3.amazonaws.com", false, true);
        updateRegion(region27, str56, "sts.ap-southeast-3.amazonaws.com", false, true);
        Region region28 = new Region("me-central-1", str113);
        arrayList8.add(region28);
        updateRegion(region28, str127, "autoscaling.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str39, "cognito-identity.me-central-1.amazonaws.com", false, true);
        String str148 = str75;
        updateRegion(region28, str148, "cognito-idp.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str138, "cognito-sync.me-central-1.amazonaws.com", false, true);
        String str149 = str138;
        updateRegion(region28, str139, "data.iot.me-central-1.amazonaws.com", false, true);
        String str150 = str129;
        updateRegion(region28, str150, "dynamodb.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str140, "ec2.me-central-1.amazonaws.com", false, true);
        String str151 = str140;
        String str152 = str141;
        updateRegion(region28, str152, "elasticloadbalancing.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str142, "firehose.me-central-1.amazonaws.com", false, true);
        String str153 = str142;
        String str154 = str143;
        updateRegion(region28, str154, "iot.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str144, "kinesis.me-central-1.amazonaws.com", false, true);
        String str155 = str144;
        String str156 = str145;
        updateRegion(region28, str156, "kms.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str146, "lambda.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str136, "logs.me-central-1.amazonaws.com", false, true);
        String str157 = str136;
        updateRegion(region28, str147, "polly.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str137, "s3.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, ServiceAbbreviations.SimpleDB, "sdb.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, ServiceAbbreviations.SNS, "sns.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str8, "sqs.me-central-1.amazonaws.com", false, true);
        updateRegion(region28, str56, "sts.me-central-1.amazonaws.com", false, true);
        Region region29 = new Region("ap-south-2", str113);
        arrayList8.add(region29);
        updateRegion(region29, str127, "autoscaling.ap-south-2.amazonaws.com", false, true);
        String str158 = str39;
        updateRegion(region29, str158, "cognito-identity.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str148, "cognito-idp.ap-south-2.amazonaws.com", false, true);
        String str159 = str148;
        updateRegion(region29, str149, "cognito-sync.ap-south-2.amazonaws.com", false, true);
        String str160 = str139;
        updateRegion(region29, str160, "data.iot.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str150, "dynamodb.ap-south-2.amazonaws.com", false, true);
        String str161 = str150;
        String str162 = str151;
        updateRegion(region29, str162, "ec2.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str152, "elasticloadbalancing.ap-south-2.amazonaws.com", false, true);
        String str163 = str152;
        String str164 = str153;
        updateRegion(region29, str164, "firehose.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str154, "iot.ap-south-2.amazonaws.com", false, true);
        String str165 = str154;
        String str166 = str155;
        updateRegion(region29, str166, "kinesis.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str156, "kms.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str146, "lambda.ap-south-2.amazonaws.com", false, true);
        String str167 = str146;
        updateRegion(region29, str157, "logs.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str147, "polly.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str137, "s3.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, ServiceAbbreviations.SimpleDB, "sdb.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, ServiceAbbreviations.SNS, "sns.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str8, "sqs.ap-south-2.amazonaws.com", false, true);
        updateRegion(region29, str56, "sts.ap-south-2.amazonaws.com", false, true);
        Region region30 = new Region("ap-southeast-4", str113);
        arrayList8.add(region30);
        String str168 = str127;
        updateRegion(region30, str168, "autoscaling.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str158, "cognito-identity.ap-southeast-4.amazonaws.com", false, true);
        String str169 = str158;
        updateRegion(region30, str159, "cognito-idp.ap-southeast-4.amazonaws.com", false, true);
        String str170 = str149;
        updateRegion(region30, str170, "cognito-sync.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str160, "data.iot.ap-southeast-4.amazonaws.com", false, true);
        String str171 = str160;
        String str172 = str161;
        updateRegion(region30, str172, "dynamodb.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str162, "ec2.ap-southeast-4.amazonaws.com", false, true);
        String str173 = str162;
        String str174 = str163;
        updateRegion(region30, str174, "elasticloadbalancing.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str164, "firehose.ap-southeast-4.amazonaws.com", false, true);
        String str175 = str164;
        String str176 = str165;
        updateRegion(region30, str176, "iot.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str166, "kinesis.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str156, "kms.ap-southeast-4.amazonaws.com", false, true);
        String str177 = str156;
        updateRegion(region30, str167, "lambda.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str157, "logs.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str147, "polly.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str137, "s3.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, ServiceAbbreviations.SimpleDB, "sdb.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, ServiceAbbreviations.SNS, "sns.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str8, "sqs.ap-southeast-4.amazonaws.com", false, true);
        updateRegion(region30, str56, "sts.ap-southeast-4.amazonaws.com", false, true);
        Region region31 = new Region("il-central-1", str113);
        arrayList8.add(region31);
        updateRegion(region31, str168, "autoscaling.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str169, "cognito-identity.il-central-1.amazonaws.com", false, true);
        String str178 = str159;
        updateRegion(region31, str178, "cognito-idp.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str170, "cognito-sync.il-central-1.amazonaws.com", false, true);
        String str179 = str170;
        String str180 = str171;
        updateRegion(region31, str180, "data.iot.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str172, "dynamodb.il-central-1.amazonaws.com", false, true);
        String str181 = str172;
        String str182 = str173;
        updateRegion(region31, str182, "ec2.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str174, "elasticloadbalancing.il-central-1.amazonaws.com", false, true);
        String str183 = str174;
        String str184 = str175;
        updateRegion(region31, str184, "firehose.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str176, "iot.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str166, "kinesis.il-central-1.amazonaws.com", false, true);
        String str185 = str166;
        updateRegion(region31, str177, "kms.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str167, "lambda.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str157, "logs.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str147, "polly.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str137, "s3.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, ServiceAbbreviations.SimpleDB, "sdb.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, ServiceAbbreviations.SNS, "sns.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str8, "sqs.il-central-1.amazonaws.com", false, true);
        updateRegion(region31, str56, "sts.il-central-1.amazonaws.com", false, true);
        Region region32 = new Region("ca-west-1", str113);
        arrayList8.add(region32);
        updateRegion(region32, str168, "autoscaling.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str169, "cognito-identity.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str178, "cognito-idp.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str179, "cognito-sync.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str180, "data.iot.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str181, "dynamodb.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str182, "ec2.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str183, "elasticloadbalancing.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str184, "firehose.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str176, "iot.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str185, "kinesis.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str177, "kms.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str167, "lambda.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str157, "logs.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str147, "polly.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str137, "s3.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, ServiceAbbreviations.SimpleDB, "sdb.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, ServiceAbbreviations.SNS, "sns.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str8, "sqs.ca-west-1.amazonaws.com", false, true);
        updateRegion(region32, str56, "sts.ca-west-1.amazonaws.com", false, true);
        return arrayList8;
    }

    private static void updateRegion(Region region, String str, String str2, boolean z, boolean z2) {
        Map<String, String> serviceEndpoints = region.getServiceEndpoints();
        Map<String, Boolean> httpSupport = region.getHttpSupport();
        Map<String, Boolean> httpsSupport = region.getHttpsSupport();
        serviceEndpoints.put(str, str2);
        httpSupport.put(str, Boolean.valueOf(z));
        httpsSupport.put(str, Boolean.valueOf(z2));
    }
}
